// Beauty Business Growth Diagnostic — INTERVENTION ONTOLOGY
// Every intervention maps to a real problem (dims) and only becomes eligible when its dimension is at
// OPPORTUNITY or worse AND its own condition holds. demandSide interventions are gated by the capacity rules.

const ALL = ['CS', 'BR', 'SR', 'SO', 'IP'];
const SOLO = ['BR', 'SR', 'IP'];
const SOLO_SO = ['BR', 'SR', 'IP', 'SO'];
const IND = ['CS', 'BR', 'SR', 'IP'];

const I = (id, o) => ({ id, personas: ALL, effort: 2, demandSide: false, prereq: [], when: null, ...o });

const INTERVENTIONS = [
  // ---------------- Demand: discovery & reputation ----------------
  I('gbp_optimization', { name: 'Google Business Profile optimization', cat: 'Discovery', dims: ['DISC', 'REP'], personas: SOLO_SO, demandSide: true, effort: 1,
    problem: 'Missing or weak presence when people nearby search for the service.',
    when: { any: [{ q: 'Q16', in: ['hard', 'nogbp', 'never', 'page1'] }, { not: { q: 'Q14', has: 'google' } }] },
    explain: 'Claim and complete your profile: categories, services, prices, hours, booking link and recent photos.',
    deliverables: ['Profile set up or cleaned up', 'Service and category list', 'Photo set', 'Booking link connected'], recur: 'one-time' }),
  I('local_seo', { name: 'Local search visibility', cat: 'Discovery', dims: ['DISC'], personas: SOLO_SO, demandSide: true, effort: 2, prereq: ['gbp_optimization'],
    problem: 'Profile exists but doesn’t rank for “[service] near me”.', when: { q: 'Q16', in: ['hard', 'page1'] },
    explain: 'Service pages, consistent listings and review velocity to move up the map results.', deliverables: ['Listing consistency', 'Service landing page', 'Monthly ranking check'], recur: 'ongoing' }),
  I('review_generation', { name: 'Review generation', cat: 'Reputation', dims: ['REP', 'DISC'], personas: SOLO_SO, effort: 1,
    problem: 'Too few recent reviews for strangers to trust you or for Google to rank you.',
    explain: 'A direct review link sent automatically after each visit, plus an in-person ask at checkout.', deliverables: ['Review link and QR', 'Automated post-visit request'], recur: 'one-time' }),
  I('review_recovery', { name: 'Review recovery', cat: 'Reputation', dims: ['REP'], personas: SOLO_SO, effort: 1,
    problem: 'Rating below 4.5 is costing trust.', when: { q: 'Q39', row: 'rating', lte: 4.2 },
    explain: 'Respond to every critical review, fix the recurring cause, and dilute old reviews with new ones.', deliverables: ['Response templates', 'Root-cause review'], recur: 'one-time' }),
  I('marketplace_profile', { name: 'Booking-app profile optimization', cat: 'Discovery', dims: ['DISC', 'ACQ'], personas: SOLO, demandSide: true, effort: 1,
    problem: 'Booking-app listing doesn’t convert browsers.', when: { q: 'Q14', has: 'apps' },
    explain: 'Specialty-led headline, portfolio, prices and reviews on the platform you already use.', deliverables: ['Profile rewrite', 'Portfolio selection'], recur: 'one-time' }),

  // ---------------- Demand: brand & positioning ----------------
  I('niche_positioning', { name: 'Specialization & positioning', cat: 'Positioning', dims: ['BRAND', 'PRICE', 'RET'], effort: 2,
    problem: 'Attracting price shoppers or ill-fitting clients; not known for anything specific.',
    when: { any: [{ q: 'Q36', in: ['mixed', 'poor'] }, { q: 'Q37', row: 'specialty', in: ['somewhat', 'no'] }, { q: 'Q27', hasAny: ['fit', 'deal'] }] },
    explain: 'Choose what you want to be known for and rebuild your menu, portfolio and profile around it.', deliverables: ['Positioning statement', 'Specialty-led menu and profile'], recur: 'one-time' }),
  I('portfolio_photography', { name: 'Portfolio & photography', cat: 'Positioning', dims: ['BRAND'], personas: IND, effort: 1,
    problem: 'Photos don’t show the work you want more of.', when: { any: [{ q: 'Q37', row: 'specialty', in: ['somewhat', 'no'] }, { q: 'Q17', in: ['inactive', 'busy_few'] }] },
    explain: 'A consistent, specialty-focused set of before/after photos — the thing people actually decide on.', deliverables: ['Shot list', 'Lighting/setup guide', 'Curated grid'], recur: 'one-time' }),
  I('instagram_strategy', { name: 'Instagram / content strategy', cat: 'Positioning', dims: ['BRAND', 'ACQ'], personas: IND, demandSide: true, effort: 2,
    problem: 'Social effort that doesn’t produce bookings, or no presence when social is the main channel.',
    when: { all: [{ q: 'Q17', in: ['busy_few', 'occasional', 'inactive'] }, { q: 'Q14', hasAny: ['ig', 'tiktok'] }] },
    explain: 'Fewer, better posts built around your specialty, with a clear booking path in every one.', deliverables: ['Content pillars', 'Monthly plan', 'Booking call-to-action'], recur: 'ongoing' }),
  I('personal_brand_cs', { name: 'Request-client building (inside a salon)', cat: 'Positioning', dims: ['ACQ', 'BRAND'], personas: ['CS'], effort: 1,
    problem: 'A book made mostly of assigned clients you don’t own.', when: { q: 'Q15', in: ['assigned', 'few', 'half'] },
    explain: 'Turn salon-assigned first visits into request clients: book their next visit with you by name, follow up personally, and make your specialty visible.', deliverables: ['First-visit-to-request routine', 'Personal booking card/link'], recur: 'one-time' }),
  I('referral_system', { name: 'Referral system', cat: 'Demand', dims: ['REF', 'ACQ'], effort: 1, demandSide: true,
    problem: 'Happy clients aren’t asked to send friends.', when: { q: 'Q38', in: ['natural', 'rarely'] },
    explain: 'A specific ask to your best clients, a simple thank-you, and a way to track who referred whom.', deliverables: ['Ask script', 'Referral card or link', 'Thank-you routine'], recur: 'one-time' }),
  I('local_partnerships', { name: 'Professional referral partnerships', cat: 'Demand', dims: ['ACQ', 'REF'], personas: SOLO, demandSide: true, effort: 2,
    problem: 'Demand depends on a single platform.', when: { q: 'Q14', countLte: 1 },
    explain: 'Relationships with complementary professionals (photographers, bridal, dermatology, fitness) who send fit clients.', deliverables: ['Partner list', 'Intro offer'], recur: 'ongoing' }),
  I('new_client_offer', { name: 'New-client offer (non-discount)', cat: 'Demand', dims: ['ACQ'], personas: SOLO_SO, demandSide: true, effort: 1,
    problem: 'Low first-visit volume with genuine open capacity.',
    when: { all: [{ not: { q: 'Q32', in: ['often', 'most'] } }, { not: { q: 'Q27', has: 'deal' } }] },
    explain: 'A value-add first visit (consultation, treatment, upgrade) rather than a discount — so you attract clients who stay.', deliverables: ['Offer design', 'Landing page copy'], recur: 'one-time' }),

  // ---------------- Conversion ----------------
  I('booking_link', { name: 'One link: work, prices, booking', cat: 'Conversion', dims: ['DIGITAL', 'CONV'], personas: SOLO, effort: 1,
    problem: 'Interested people have to ask before they can book.', when: { any: [{ q: 'Q37', row: 'link', in: ['partial', 'none'] }, { q: 'Q18', in: ['dm', 'call'] }] },
    explain: 'One mobile page with your specialty, portfolio, real prices and a booking button — linked from every profile.', deliverables: ['Booking page', 'Link placement'], recur: 'one-time' }),
  I('online_booking', { name: 'Online booking setup', cat: 'Conversion', dims: ['CONV', 'AUTO'], personas: SOLO, effort: 1,
    problem: 'Message-first booking adds friction and admin.', when: { q: 'Q18', in: ['dm', 'call', 'mix'] },
    explain: 'Let clients book themselves, with deposits and intake questions built in.', deliverables: ['Booking software configured', 'Service durations and buffers'], recur: 'one-time' }),
  I('inquiry_response', { name: 'Inquiry response & speed-to-lead', cat: 'Conversion', dims: ['CONV'], personas: SOLO, effort: 1,
    problem: 'Slow or inconsistent replies lose ready clients.', when: { any: [{ q: 'Q19', in: ['next', 'slow', 'same'] }, { q: 'Q20', lte: 0.45 }] },
    explain: 'Instant auto-reply with your booking link and prices, saved replies for common questions, and a set reply window.', deliverables: ['Auto-replies', 'Saved replies', 'Reply routine'], recur: 'one-time' }),
  I('missed_inquiry_recovery', { name: 'Unbooked inquiry follow-up', cat: 'Conversion', dims: ['CONV'], personas: SOLO, effort: 1,
    problem: 'People who asked but didn’t book are never followed up.', when: { any: [{ q: 'Q20', lte: 0.45 }, { q: 'Q19', in: ['slow'] }] },
    explain: 'A weekly sweep of unbooked inquiries with one friendly follow-up and a direct link.', deliverables: ['Follow-up template', 'Weekly sweep'], recur: 'one-time' }),

  // ---------------- Leakage ----------------
  I('deposit_policy', { name: 'Deposit / card-on-file policy', cat: 'Leakage', dims: ['CXL'], personas: SOLO, effort: 1,
    problem: 'No financial reason to keep or reschedule an appointment.', when: { any: [{ q: 'Q22', in: ['soft', 'none'] }, { not: { q: 'Q22', in: ['deposit', 'card'] } }] },
    explain: 'Require a deposit or card on file at booking, stated clearly and applied consistently.', deliverables: ['Policy wording', 'Booking-software settings', 'Script for existing clients'], recur: 'one-time' }),
  I('cancellation_policy', { name: 'Cancellation policy enforcement', cat: 'Leakage', dims: ['CXL'], personas: SOLO, effort: 1,
    problem: 'A policy exists but isn’t enforced.', when: { q: 'Q22', in: ['soft'] },
    explain: 'Make enforcement automatic so it isn’t a personal confrontation each time.', deliverables: ['Automated fee capture', 'Grace rule'], recur: 'one-time' }),
  I('reminders_confirmations', { name: 'Automated reminders & confirmations', cat: 'Leakage', dims: ['CXL', 'AUTO'], personas: IND, effort: 1,
    problem: 'Clients forget or don’t confirm.', when: { not: { q: 'Q40', row: 'auto', in: ['most'] } },
    explain: 'Two-step reminders (e.g., 48h confirm + same-day) with one-tap reschedule.', deliverables: ['Reminder sequence'], recur: 'one-time' }),
  I('waitlist_system', { name: 'Waitlist & last-minute refill', cat: 'Leakage', dims: ['CXL', 'UTIL'], personas: IND, effort: 1,
    problem: 'Openings stay empty even when people want in.', when: { any: [{ q: 'Q23', in: ['empty', 'manual'] }, { q: 'Q10', in: ['four', 'turning'] }] },
    explain: 'A standing waitlist that is notified automatically when a slot opens.', deliverables: ['Waitlist setup', 'Opening alert'], recur: 'one-time' }),
  I('cancellation_recovery', { name: 'Cancellation recovery routine', cat: 'Leakage', dims: ['CXL'], personas: IND, effort: 1,
    problem: 'Cancelled clients aren’t rebooked.', when: { q: 'Q23', in: ['empty'] },
    explain: 'Every cancellation gets an immediate reschedule link, and the slot goes to the waitlist.', deliverables: ['Reschedule message', 'Routine'], recur: 'one-time' }),

  // ---------------- Retention ----------------
  I('prebooking_system', { name: 'Prebooking at checkout', cat: 'Retention', dims: ['REBOOK', 'RET'], effort: 1,
    problem: 'Clients leave without their next visit booked.',
    explain: 'Recommend the specific next date based on the service (“I’d like to see you on the 14th”), book it before they stand up, and confirm by text.', deliverables: ['Checkout script', 'Interval chart by service', 'Prebook tracking'], recur: 'one-time' }),
  I('first_visit_followup', { name: 'Second-visit system', cat: 'Retention', dims: ['RET'], effort: 1,
    problem: 'First-time clients don’t return.',
    explain: 'A next-day check-in, a care tip, and a rebook nudge at the right interval for every new client.', deliverables: ['New-client sequence', 'Return-rate tracking'], recur: 'one-time' }),
  I('retention_system', { name: 'Overdue-client tracking', cat: 'Retention', dims: ['RET', 'REACT'], effort: 1,
    problem: 'Regulars drift away unnoticed.', when: { any: [{ q: 'Q29', in: ['nothing', 'occasional'] }, { not: { q: 'Q29', in: ['auto'] } }] },
    explain: 'Flag clients who pass their normal interval and reach out personally before they’re gone.', deliverables: ['Overdue list', 'Check-in message'], recur: 'one-time' }),
  I('membership', { name: 'Membership / maintenance plan', cat: 'Retention', dims: ['REBOOK', 'RET', 'TICKET'], personas: SOLO_SO, effort: 2,
    problem: 'Short-cycle clients book irregularly.', when: { all: [{ any: [{ q: 'Q03', in: ['lash', 'nails', 'barber', 'brow', 'skin', 'wax'] }, { q: 'Q26', lte: 4 }] }, { q: 'Q25', gte: 0.65 }] },
    explain: 'A monthly plan covering standard maintenance visits — predictable revenue for you, guaranteed spots for them.', deliverables: ['Plan design and pricing', 'Billing setup'], recur: 'one-time' }),
  I('vip_strategy', { name: 'Top-client care', cat: 'Retention', dims: ['RET', 'TICKET'], effort: 1,
    problem: 'Best clients get the same treatment as everyone else.', when: { q: 'Q25', gte: 0.65 },
    explain: 'Identify your top 20% and give them first access to prime times, new services and a personal touch.', deliverables: ['Top-client list', 'Perks'], recur: 'one-time' }),
  I('win_back', { name: 'Past-client reactivation', cat: 'Reactivation', dims: ['REACT'], effort: 1,
    problem: 'A large list of lapsed clients is never invited back.', when: { q: 'Q28', row: 'count', gte: 200 },
    explain: 'A personal, specific invitation to clients overdue by more than one cycle — segmented by service.', deliverables: ['Lapsed-client list', 'Invitation sequence', 'Response tracking'], recur: 'one-time' }),
  I('database_cleanup', { name: 'Client list cleanup', cat: 'Reactivation', dims: ['REACT', 'AUTO'], effort: 1,
    problem: 'Client info scattered across phone, DMs or paper.', when: { q: 'Q28', row: 'where', in: ['phone', 'paper', 'scattered', 'partial'] },
    explain: 'Consolidate contacts and visit history into one system so follow-up becomes possible.', deliverables: ['Consolidated client list'], recur: 'one-time' }),
  I('email_sms_program', { name: 'Client messaging program', cat: 'Reactivation', dims: ['REACT', 'RET'], effort: 2,
    problem: 'No ongoing contact between visits.', when: { q: 'Q28', row: 'count', gte: 500 },
    explain: 'A light monthly message — openings, seasonal services, care tips — to stay top of mind.', deliverables: ['Monthly message calendar'], recur: 'ongoing' }),

  // ---------------- Monetization ----------------
  I('pricing_analysis', { name: 'Pricing analysis', cat: 'Monetization', dims: ['PRICE', 'MIX'], personas: ['BR', 'SR', 'IP', 'SO'], effort: 1,
    problem: 'Prices haven’t kept pace with demand, skill or costs.',
    explain: 'Revenue per hour by service, local comparison at your skill level, and demand signals — before changing anything.', deliverables: ['Revenue-per-hour by service', 'Local comparison', 'Recommendation'], recur: 'one-time' }),
  I('price_increase_plan', { name: 'Price increase plan', cat: 'Monetization', dims: ['PRICE'], personas: ['BR', 'SR', 'IP', 'SO'], effort: 1, prereq: ['pricing_analysis'],
    problem: 'Full book with stagnant prices.', when: { any: [{ q: 'Q09', gte: 0.82 }, { q: 'Q10', in: ['four', 'turning'] }, { q: 'Q48', in: ['full'] }] },
    explain: 'Raise prices for new clients first, then regulars with notice, starting with your most in-demand services.', deliverables: ['New price list', 'Client announcement', 'Rollout timing'], recur: 'one-time' }),
  I('career_tier_plan', { name: 'Level / tier progression plan', cat: 'Monetization', dims: ['PRICE', 'TICKET'], personas: ['CS'], effort: 1,
    problem: 'Commission stylist’s price level or percentage hasn’t moved.',
    explain: 'Know the productivity numbers that move you to the next level — and bring them to a conversation with your salon.', deliverables: ['Your numbers', 'Next-level criteria', 'Conversation outline'], recur: 'one-time' }),
  I('discount_reduction', { name: 'Discount reduction', cat: 'Monetization', dims: ['PRICE', 'TICKET'], effort: 1,
    problem: 'Discounting trains clients to wait for deals.', when: { any: [{ q: 'Q32', in: ['often', 'most'] }, { q: 'Q27', has: 'deal' }] },
    explain: 'Replace discounts with value-adds, and phase out standing discounts for regulars.', deliverables: ['Discount inventory', 'Replacement offers'], recur: 'one-time' }),
  I('service_profitability', { name: 'Service profitability review', cat: 'Monetization', dims: ['MIX'], personas: IND, effort: 1,
    problem: 'Low-value services consume valuable hours.', when: { q: 'Q35', in: ['no', 'partly', 'unsure'] },
    explain: 'Revenue per hour for every service; reprice, restructure, limit or drop the ones that don’t pay.', deliverables: ['Service-by-service table', 'Decisions'], recur: 'one-time' }),
  I('menu_restructure', { name: 'Service menu restructuring', cat: 'Monetization', dims: ['MIX', 'TICKET'], personas: ['BR', 'SR', 'IP', 'SO'], effort: 2,
    problem: 'Menu encourages low-value bookings.', when: { any: [{ q: 'Q35', in: ['no'] }, { q: 'Q34', row: 'addon', in: ['rare', 'none'] }] },
    explain: 'Bundle services into packages, price by time and complexity, and make upgrades part of booking.', deliverables: ['New menu'], recur: 'one-time' }),
  I('addon_strategy', { name: 'Add-on strategy', cat: 'Monetization', dims: ['TICKET'], effort: 1,
    problem: 'Clients rarely add services that would improve results.', when: { q: 'Q34', row: 'addon', in: ['rare', 'none', 'some'] },
    explain: 'Two or three add-ons that genuinely improve results, offered at booking and recommended in the chair.', deliverables: ['Add-on list and pricing', 'Booking-flow upsell', 'Chair-side script'], recur: 'one-time' }),
  I('retail_strategy', { name: 'Retail strategy', cat: 'Monetization', dims: ['RETAIL'], effort: 1,
    problem: 'Clients leave without the products that maintain their results.', when: { q: 'Q34', row: 'retail', lte: 200 },
    explain: 'A small, focused shelf and a specific home-care prescription at relevant visits.', deliverables: ['Product edit', 'Prescription card', 'Display'], recur: 'one-time' }),
  I('schedule_architecture', { name: 'Schedule architecture', cat: 'Capacity', dims: ['UTIL', 'MIX'], personas: IND, effort: 1,
    problem: 'Gaps, fragments and low-value services in prime time.', when: { any: [{ q: 'Q12', has: 'scattered' }, { q: 'Q35', in: ['no', 'partly'] }, { q: 'Q09', gte: 0.82 }] },
    explain: 'Booking rules that protect prime hours for high-value services and eliminate unusable gaps.', deliverables: ['Booking rules', 'Template week'], recur: 'one-time' }),
  I('working_hours', { name: 'Working-hours optimization', cat: 'Capacity', dims: ['UTIL'], personas: SOLO, effort: 1,
    problem: 'Available hours don’t match when clients want to come.', when: { q: 'Q12', hasAny: ['wk_morn', 'wk_aft'] },
    explain: 'Move hours from slow periods to when your clients actually book.', deliverables: ['Demand-by-hour review', 'New schedule'], recur: 'one-time' }),
  I('capacity_analysis', { name: 'Capacity decision', cat: 'Capacity', dims: ['UTIL', 'PRICE'], personas: SOLO, effort: 1,
    problem: 'Overbooked — the next step could be price, hours, an assistant or a waitlist.', when: { any: [{ q: 'Q10', in: ['turning'] }, { q: 'Q09', gte: 0.93 }] },
    explain: 'Decide in order: raise prices, restructure the menu, then consider added hours or help.', deliverables: ['Capacity model', 'Decision'], recur: 'one-time' }),
  I('rent_economics', { name: 'Rent & breakeven review', cat: 'Monetization', dims: ['UTIL', 'PRICE'], personas: ['BR', 'SR'], effort: 1,
    problem: 'Fixed rent consumes too much of weekly revenue.', when: null,
    explain: 'Appointments needed to cover rent, and whether pricing or utilization is the faster way to improve it.', deliverables: ['Breakeven math'], recur: 'one-time' }),
  I('salon_conversation', { name: 'What to ask your salon for', cat: 'Positioning', dims: ['ACQ', 'CXL', 'PRICE'], personas: ['CS'], effort: 1,
    problem: 'Levers controlled by the salon (policy, lead routing, price level).',
    explain: 'A specific, numbers-backed conversation: review links that name you, fair lead routing, policy enforcement, and your path to the next level.', deliverables: ['Conversation outline'], recur: 'one-time' }),

  // ---------------- Systems ----------------
  I('booking_automation', { name: 'Booking & follow-up automation', cat: 'Systems', dims: ['AUTO'], personas: SOLO, effort: 1,
    problem: 'Routine follow-up depends on remembering.',
    explain: 'Turn on confirmations, reminders, rebook nudges, review requests and overdue alerts in the software you already pay for.', deliverables: ['Automation setup'], recur: 'one-time' }),
  I('financial_dashboard', { name: 'Simple numbers dashboard', cat: 'Systems', dims: ['FIN'], effort: 1,
    problem: 'Decisions made without the key numbers.',
    explain: 'Five numbers, monthly: revenue, revenue per hour, prebook rate, first-visit return rate, new clients.', deliverables: ['One-page dashboard'], recur: 'one-time' }),

  // ---------------- Salon owner ----------------
  I('recruiting_funnel', { name: 'Stylist recruiting pipeline', cat: 'People', dims: ['RECRUIT', 'CHAIR_UTIL'], personas: ['SO'], effort: 2,
    problem: 'Chairs empty because good stylists are hard to find.',
    explain: 'A careers page, a clear offer, school and educator relationships, and staff referral bonuses — running before you need someone.', deliverables: ['Careers page', 'Offer sheet', 'Sourcing channels', 'Interview process'], recur: 'ongoing' }),
  I('apprenticeship_program', { name: 'Apprentice / associate program', cat: 'People', dims: ['RECRUIT', 'STAFF_RET'], personas: ['SO'], effort: 3,
    problem: 'Experienced stylists are scarce or leave for suites.', when: { q: 'Q44', in: ['months', 'open', 'wom'] },
    explain: 'Grow your own: hire newer stylists into a structured path with education and a ramp to a full book.', deliverables: ['Program outline', 'Ramp milestones'], recur: 'ongoing' }),
  I('chair_utilization_strategy', { name: 'Empty-chair decision', cat: 'People', dims: ['CHAIR_UTIL'], personas: ['SO'], effort: 1,
    problem: 'Empty stations with no plan.',
    explain: 'For each empty station: recruit, rent, or repurpose — based on demand and economics.', deliverables: ['Chair-by-chair plan'], recur: 'one-time' }),
  I('booth_rental_strategy', { name: 'Rental as a bridge', cat: 'People', dims: ['CHAIR_UTIL'], personas: ['SO'], effort: 1,
    problem: 'Empty chairs produce nothing while recruiting takes months.', when: { q: 'Q43', hasAny: ['recruit', 'left', 'economics', 'not_tried'] },
    explain: 'Rent an empty chair at a fair rate while you recruit — guaranteed income instead of none.', deliverables: ['Rental terms', 'Listing'], recur: 'one-time' }),
  I('stylist_dashboard', { name: 'Stylist performance dashboard', cat: 'Operations', dims: ['STYLIST_PROD', 'OPS'], personas: ['SO'], effort: 1,
    problem: 'No visibility into each stylist’s numbers.',
    explain: 'Weekly booked %, revenue, prebook rate, retention and retail by stylist — reviewed together, not used as a weapon.', deliverables: ['Dashboard', 'Weekly review routine'], recur: 'one-time' }),
  I('stylist_coaching', { name: 'Stylist rebooking & retail coaching', cat: 'Operations', dims: ['STYLIST_PROD', 'REBOOK', 'RETAIL', 'TICKET'], personas: ['SO'], effort: 2,
    problem: 'Salon-level rebooking, ticket or retail lag.',
    explain: 'Coach the checkout moment: next-visit recommendation, home-care prescription, add-on — by stylist, with their own numbers.', deliverables: ['Checkout standard', 'Monthly 1:1s'], recur: 'ongoing' }),
  I('lead_distribution', { name: 'Lead routing', cat: 'Operations', dims: ['LEAD_DIST', 'STYLIST_PROD'], personas: ['SO'], effort: 1,
    problem: 'New clients assigned randomly or not at all.', when: { q: 'Q47', row: 'assign', in: ['avail', 'rotation', 'none', 'own'] },
    explain: 'Route new clients by specialty and capacity, toward stylists who need to grow — and track who keeps them.', deliverables: ['Routing rules', 'Second-visit rate by stylist'], recur: 'one-time' }),
  I('front_desk_conversion', { name: 'Front-desk conversion', cat: 'Operations', dims: ['LEAD_DIST', 'CONV'], personas: ['SO'], effort: 2,
    problem: 'Calls and messages handled between clients or by the owner.', when: { q: 'Q47', row: 'who', in: ['stylists', 'owner'] },
    explain: 'A dedicated (or shared/virtual) desk role with a booking script, response standard and missed-call text-back.', deliverables: ['Desk standard', 'Scripts', 'Text-back'], recur: 'one-time' }),
  I('salon_retention_program', { name: 'Salon-level client retention', cat: 'Operations', dims: ['RET', 'OPS'], personas: ['SO'], effort: 2,
    problem: 'Clients belong to individual stylists, not the salon.',
    explain: 'Salon-owned records, salon-level follow-up and overdue outreach, and team introductions so clients know more than one person.', deliverables: ['Salon follow-up sequence', 'Team-care practices'], recur: 'one-time' }),
  I('staff_retention', { name: 'Stylist retention & career path', cat: 'People', dims: ['STAFF_RET'], personas: ['SO'], effort: 2,
    problem: 'Good stylists leave within a few years.',
    explain: 'Productivity-based tiers, education, and a path that makes staying more attractive than going solo.', deliverables: ['Tier structure', 'Education plan', 'Stay interviews'], recur: 'one-time' }),
  I('career_path', { name: 'Visible career levels', cat: 'People', dims: ['STAFF_RET', 'RECRUIT'], personas: ['SO'], effort: 1,
    problem: 'Stylists can’t see how to grow inside the salon.', when: { q: 'Q45', lte: 1.5 },
    explain: 'Written levels with clear numbers for each step.', deliverables: ['Level document'], recur: 'one-time' }),
  I('commission_review', { name: 'Commission & chair economics review', cat: 'Operations', dims: ['OPS', 'STYLIST_PROD'], personas: ['SO'], effort: 1,
    problem: 'Unclear margin per stylist; some chairs may lose money.',
    explain: 'Contribution margin per stylist after commission, product and overhead — and a structure that rewards productivity.', deliverables: ['Margin by stylist', 'Structure recommendation'], recur: 'one-time' }),
  I('owner_transition_plan', { name: 'Owner chair-transition plan', cat: 'Owner leverage', dims: ['OWNER_DEP'], personas: ['SO'], effort: 2,
    problem: 'Salon revenue depends on the owner’s chair.', when: { any: [{ q: 'Q53', in: ['reduce', 'step', 'unsure'] }, { q: 'Q51', gte: 0.4 }] },
    explain: 'A 12-month plan to move your clients and responsibilities: who takes which clients, what you raise, and what you delegate.', deliverables: ['Target owner share', 'Client transition plan', 'Delegation list'], recur: 'one-time' }),
  I('manager_role', { name: 'Manager / lead role', cat: 'Owner leverage', dims: ['OWNER_DEP', 'OPS'], personas: ['SO'], effort: 3,
    problem: 'Every operational question lands on the owner.', when: { any: [{ q: 'Q54', in: ['fires', 'admin', 'none'] }, { q: 'Q52', in: ['serious', 'couldnt'] }] },
    explain: 'Define a lead or manager role that owns the daily operation, with clear authority.', deliverables: ['Role definition', 'Handover list'], recur: 'one-time' }),
  I('operational_systems', { name: 'Core salon routines', cat: 'Operations', dims: ['OPS'], personas: ['SO'], effort: 2,
    problem: 'The salon runs on the owner’s memory.',
    explain: 'Written standards for front desk, checkout, rebooking, onboarding, and the weekly numbers review.', deliverables: ['Five routines documented', 'Onboarding checklist'], recur: 'one-time' }),
];

const INT = Object.fromEntries(INTERVENTIONS.map((x) => [x.id, x]));

// ---------------- WHAT I WOULDN'T SPEND MONEY ON (catalog) ----------------
// Selected by rules (see rules.js). Mandatory section: at least one item always appears.
const DONT_BUY = {
  ads: { title: 'Paid advertising for new clients', personas: ['CS', 'BR', 'SR', 'IP'] },
  salon_ads: { title: 'Advertising for more salon customers', personas: ['SO'] },
  followers: { title: 'Growing your follower count', personas: ['CS', 'BR', 'SR', 'IP', 'SO'] },
  discounts: { title: 'New-client discounts and deal promotions', personas: ['BR', 'SR', 'IP', 'SO', 'CS'] },
  website_rebuild: { title: 'A full website rebuild', personas: ['BR', 'SR', 'IP', 'SO'] },
  seo_package: { title: 'An SEO retainer', personas: ['BR', 'SR', 'IP', 'SO'] },
  more_capacity: { title: 'More hours, an assistant or a bigger space — yet', personas: ['BR', 'SR', 'IP'] },
  recruit_first: { title: 'Recruiting more stylists — yet', personas: ['SO'] },
  new_software: { title: 'Switching booking software', personas: ['BR', 'SR', 'IP', 'SO'] },
  marketing_overhaul: { title: 'A broad marketing overhaul', personas: ['CS', 'BR', 'SR', 'IP', 'SO'] },
  personal_marketing_cs: { title: 'Paying for your own advertising', personas: ['CS'] },
};

module.exports = { INTERVENTIONS, INT, DONT_BUY };
